### ISSUE TITLE
IIIFIngestJob failed to ingest manifest "https://figgy.princeton.edu/concern/scanned_resources/e6bac95b-de4a-4692-afab-3fc604ec1938/manifest"

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/dpul#1021]
This comes up when reindexing a whole collection. Maybe it failed to get the manifest or something?

## Backtrace

    line 92 of [PROJECT_ROOT]/app/models/iiif_resource.rb: set_noid
    line 61 of [PROJECT_ROOT]/app/models/iiif_resource.rb: save_and_index_now
    line 24 of [PROJECT_ROOT]/app/jobs/iiif_ingest_job.rb: ingest

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/51733/faults/81455332)

## Job Arguments

```ruby
{
  "context" => "Job raised exception",
  "job" => {
    "class" => "ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper",
    "wrapped" => "IIIFIngestJob",
    "queue" => "default",
    "args" => [{
      "job_class" => "IIIFIngestJob",
      "job_id" => "e482847b-913b-4a51-b1f1-b58c5b8cc593",
      "provider_job_id" => nil,
      "queue_name" => "default",
      "priority" => nil,
      "arguments" => [
        "https://figgy.princeton.edu/concern/scanned_resources/e6bac95b-de4a-4692-afab-3fc604ec1938/manifest",
        {"_aj_globalid" => "gid://pomegranate/Spotlight::Exhibit/106"},
        nil
      ],
      "executions" => 0,
      "locale" => "en"
    }],
    "retry" => true,
    "jid" => "6d5a8d4b31106faa77a5f176",
    "created_at" => 1632931716.2732897,
    "enqueued_at" => 1632933763.0633185,
    "error_message" => "Failed to update Solr for the following documents: (id: 759171f007bec23714aaeaaa118cf7cb, noid: 0z708x04j)",
    "error_class" => "IIIFResource::IndexingError",
    "failed_at" => 1632933731.4161365,
    "retry_count" => 0
  },
  "jobstr" => "{\"class\":\"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper\",\"wrapped\":\"IIIFIngestJob\",\"queue\":\"default\",\"args\":[{\"job_class\":\"IIIFIngestJob\",\"job_id\":\"e482847b-913b-4a51-b1f1-b58c5b8cc593\",\"provider_job_id\":null,\"queue_name\":\"default\",\"priority\":null,\"arguments\":[\"https://figgy.princeton.edu/concern/scanned_resources/e6bac95b-de4a-4692-afab-3fc604ec1938/manifest\",{\"_aj_globalid\":\"gid://pomegranate/Spotlight::Exhibit/106\"},null],\"executions\":0,\"locale\":\"en\"}],\"retry\":true,\"jid\":\"6d5a8d4b31106faa77a5f176\",\"created_at\":1632931716.2732897,\"enqueued_at\":1632933763.0633185,\"error_message\":\"Failed to update Solr for the following documents: (id: 759171f007bec23714aaeaaa118cf7cb, noid: 0z708x04j)\",\"error_class\":\"IIIFResource::IndexingError\",\"failed_at\":1632933731.4161365,\"retry_count\":0}"
}
```

## Full Backtrace

```
/opt/dpul/releases/20210917182847/app/models/iiif_resource.rb:92:in `set_noid'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.5/lib/active_support/callbacks.rb:426:in `block in make_lambda'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.5/lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.5/lib/active_support/callbacks.rb:606:in `block (2 levels) in default_terminator'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.5/lib/active_support/callbacks.rb:605:in `catch'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.5/lib/active_support/callbacks.rb:605:in `block in default_terminator'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.5/lib/active_support/callbacks.rb:199:in `block in halting'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.5/lib/active_support/callbacks.rb:513:in `block in invoke_before'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.5/lib/active_support/callbacks.rb:513:in `each'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.5/lib/active_support/callbacks.rb:513:in `invoke_before'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.5/lib/active_support/callbacks.rb:131:in `run_callbacks'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.5/lib/active_support/callbacks.rb:816:in `_run_save_callbacks'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/callbacks.rb:342:in `create_or_update'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/persistence.rb:275:in `save'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/validations.rb:46:in `save'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/transactions.rb:310:in `block (2 levels) in save'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/transactions.rb:387:in `block in with_transaction_returning_status'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `block in transaction'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction'
/usr/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `transaction'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/transactions.rb:212:in `transaction'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/transactions.rb:385:in `with_transaction_returning_status'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/transactions.rb:310:in `block in save'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/transactions.rb:325:in `rollback_active_record_state!'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/transactions.rb:309:in `save'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/suppressor.rb:44:in `save'
/opt/dpul/releases/20210917182847/app/models/iiif_resource.rb:61:in `save_and_index_now'
/opt/dpul/releases/20210917182847/app/jobs/iiif_ingest_job.rb:24:in `ingest'
/opt/dpul/releases/20210917182847/app/jobs/iiif_ingest_job.rb:8:in `block in perform'
/opt/dpul/releases/20210917182847/app/jobs/iiif_ingest_job.rb:7:in `each'
/opt/dpul/releases/20210917182847/app/jobs/iiif_ingest_job.rb:7:in `perform'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activejob-5.2.4.5/lib/active_job/execution.rb:39:in `block in perform_now'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.5/lib/active_support/callbacks.rb:109:in `block in run_callbacks'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/i18n-1.8.10/lib/i18n.rb:314:in `with_locale'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activejob-5.2.4.5/lib/active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.5/lib/active_support/callbacks.rb:118:in `instance_exec'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.5/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activejob-5.2.4.5/lib/active_job/logging.rb:26:in `block (4 levels) in <module:Logging>'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.5/lib/active_support/notifications.rb:168:in `block in instrument'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.5/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.5/lib/active_support/notifications.rb:168:in `instrument'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activejob-5.2.4.5/lib/active_job/logging.rb:25:in `block (3 levels) in <module:Logging>'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activejob-5.2.4.5/lib/active_job/logging.rb:46:in `block in tag_logger'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.5/lib/active_support/tagged_logging.rb:71:in `block in tagged'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.5/lib/active_support/tagged_logging.rb:28:in `tagged'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.5/lib/active_support/tagged_logging.rb:71:in `tagged'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activejob-5.2.4.5/lib/active_job/logging.rb:46:in `tag_logger'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activejob-5.2.4.5/lib/active_job/logging.rb:22:in `block (2 levels) in <module:Logging>'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.5/lib/active_support/callbacks.rb:118:in `instance_exec'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.5/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.5/lib/active_support/callbacks.rb:136:in `run_callbacks'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activejob-5.2.4.5/lib/active_job/execution.rb:38:in `perform_now'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activejob-5.2.4.5/lib/active_job/execution.rb:24:in `block in execute'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.5/lib/active_support/callbacks.rb:109:in `block in run_callbacks'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activejob-5.2.4.5/lib/active_job/railtie.rb:28:in `block (4 levels) in <class:Railtie>'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.5/lib/active_support/execution_wrapper.rb:87:in `wrap'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.5/lib/active_support/reloader.rb:73:in `block in wrap'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.5/lib/active_support/execution_wrapper.rb:83:in `wrap'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.5/lib/active_support/reloader.rb:72:in `wrap'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activejob-5.2.4.5/lib/active_job/railtie.rb:27:in `block (3 levels) in <class:Railtie>'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.5/lib/active_support/callbacks.rb:118:in `instance_exec'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.5/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.5/lib/active_support/callbacks.rb:136:in `run_callbacks'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activejob-5.2.4.5/lib/active_job/execution.rb:22:in `execute'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activejob-5.2.4.5/lib/active_job/queue_adapters/sidekiq_adapter.rb:42:in `perform'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/sidekiq-5.2.9/lib/sidekiq/processor.rb:192:in `execute_job'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/sidekiq-5.2.9/lib/sidekiq/processor.rb:165:in `block (2 levels) in process'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/sidekiq-5.2.9/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/ddtrace-0.49.0/lib/ddtrace/contrib/sidekiq/server_tracer.rb:42:in `block in call'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/ddtrace-0.49.0/lib/ddtrace/tracer.rb:287:in `trace'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/ddtrace-0.49.0/lib/ddtrace/contrib/sidekiq/server_tracer.rb:23:in `call'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/sidekiq-5.2.9/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/honeybadger-4.8.0/lib/honeybadger/plugins/sidekiq.rb:10:in `call'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/sidekiq-5.2.9/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/sidekiq-5.2.9/lib/sidekiq/middleware/chain.rb:133:in `invoke'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/sidekiq-5.2.9/lib/sidekiq/processor.rb:164:in `block in process'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/sidekiq-5.2.9/lib/sidekiq/processor.rb:137:in `block (6 levels) in dispatch'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/sidekiq-5.2.9/lib/sidekiq/job_retry.rb:109:in `local'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/sidekiq-5.2.9/lib/sidekiq/processor.rb:136:in `block (5 levels) in dispatch'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/sidekiq-5.2.9/lib/sidekiq/rails.rb:43:in `block in call'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.5/lib/active_support/execution_wrapper.rb:87:in `wrap'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.5/lib/active_support/reloader.rb:73:in `block in wrap'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.5/lib/active_support/execution_wrapper.rb:87:in `wrap'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.5/lib/active_support/reloader.rb:72:in `wrap'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/sidekiq-5.2.9/lib/sidekiq/rails.rb:42:in `call'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/sidekiq-5.2.9/lib/sidekiq/processor.rb:132:in `block (4 levels) in dispatch'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/sidekiq-5.2.9/lib/sidekiq/processor.rb:250:in `stats'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/sidekiq-5.2.9/lib/sidekiq/processor.rb:127:in `block (3 levels) in dispatch'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/sidekiq-5.2.9/lib/sidekiq/job_logger.rb:8:in `call'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/sidekiq-5.2.9/lib/sidekiq/processor.rb:126:in `block (2 levels) in dispatch'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/sidekiq-5.2.9/lib/sidekiq/job_retry.rb:74:in `global'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/sidekiq-5.2.9/lib/sidekiq/processor.rb:125:in `block in dispatch'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/sidekiq-5.2.9/lib/sidekiq/logging.rb:48:in `with_context'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/sidekiq-5.2.9/lib/sidekiq/logging.rb:42:in `with_job_hash_context'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/sidekiq-5.2.9/lib/sidekiq/processor.rb:124:in `dispatch'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/sidekiq-5.2.9/lib/sidekiq/processor.rb:163:in `process'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/sidekiq-5.2.9/lib/sidekiq/processor.rb:83:in `process_one'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/sidekiq-5.2.9/lib/sidekiq/processor.rb:71:in `run'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/sidekiq-5.2.9/lib/sidekiq/util.rb:16:in `watchdog'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/sidekiq-5.2.9/lib/sidekiq/util.rb:25:in `block in safe_thread'
```

**Comment by hackartisan** [comment]
Haven't seen this since September and we just did a reindex.
