### ISSUE TITLE
[DPUL/production] NoMethodError: undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/dpul#949]
I think what's happening is that there is an error when value in the metadata hash is nil. Method should have a guard clause.

https://github.com/pulibrary/dpul/blob/main/app/values/manifest_metadata.rb#L71

## Backtrace

    line 71 of [PROJECT_ROOT]/app/values/manifest_metadata.rb: block in transform_value
    line 71 of [PROJECT_ROOT]/app/values/manifest_metadata.rb: each
    line 71 of [PROJECT_ROOT]/app/values/manifest_metadata.rb: transform_value

## Full Backtrace

```

/opt/dpul/releases/20210917182847/app/values/manifest_metadata.rb:71:in `block in transform_value'
/opt/dpul/releases/20210917182847/app/values/manifest_metadata.rb:71:in `each'
/opt/dpul/releases/20210917182847/app/values/manifest_metadata.rb:71:in `transform_value'
/opt/dpul/releases/20210917182847/app/values/manifest_metadata.rb:66:in `block in new_values'
/opt/dpul/releases/20210917182847/app/values/manifest_metadata.rb:66:in `map'
/opt/dpul/releases/20210917182847/app/values/manifest_metadata.rb:66:in `new_values'
/opt/dpul/releases/20210917182847/app/values/manifest_metadata.rb:50:in `to_pair'
/opt/dpul/releases/20210917182847/app/values/manifest_metadata.rb:109:in `block in process_values'
/opt/dpul/releases/20210917182847/app/values/manifest_metadata.rb:108:in `each'
/opt/dpul/releases/20210917182847/app/values/manifest_metadata.rb:108:in `map'
/opt/dpul/releases/20210917182847/app/values/manifest_metadata.rb:108:in `process_values'
/opt/dpul/releases/20210917182847/app/values/manifest_metadata.rb:117:in `metadata_hash'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/blacklight-spotlight-2.13.0/app/models/spotlight/resources/iiif_manifest.rb:184:in `to_solr'
/opt/dpul/releases/20210917182847/app/services/iiif_manifest.rb:95:in `manifest_metadata'
/opt/dpul/releases/20210917182847/app/services/iiif_manifest.rb:7:in `to_solr'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/blacklight-spotlight-2.13.0/app/services/spotlight/resources/iiif_builder.rb:13:in `block in to_solr'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/blacklight-spotlight-2.13.0/app/models/spotlight/resources/iiif_service.rb:55:in `each'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/blacklight-spotlight-2.13.0/app/models/spotlight/resources/iiif_service.rb:55:in `recursive_manifests'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/blacklight-spotlight-2.13.0/app/services/spotlight/resources/iiif_builder.rb:11:in `each'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/blacklight-spotlight-2.13.0/app/services/spotlight/resources/iiif_builder.rb:11:in `to_solr'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/blacklight-spotlight-2.13.0/app/services/spotlight/solr_document_builder.rb:23:in `each'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/blacklight-spotlight-2.13.0/app/services/spotlight/solr_document_builder.rb:23:in `each'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/blacklight-spotlight-2.13.0/app/services/spotlight/solr_document_builder.rb:23:in `each'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/blacklight-spotlight-2.13.0/app/services/spotlight/solr_document_builder.rb:23:in `each'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/blacklight-spotlight-2.13.0/app/services/spotlight/solr_document_builder.rb:23:in `documents_to_index'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/blacklight-spotlight-2.13.0/app/models/spotlight/resource.rb:54:in `each'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/blacklight-spotlight-2.13.0/app/models/spotlight/resource.rb:54:in `each_slice'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/blacklight-spotlight-2.13.0/app/models/spotlight/resource.rb:54:in `block (2 levels) in reindex'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.5/lib/active_support/callbacks.rb:132:in `run_callbacks'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/blacklight-spotlight-2.13.0/app/models/spotlight/resource.rb:53:in `block in reindex'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.5/lib/active_support/benchmarkable.rb:43:in `block in benchmark'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.5/lib/active_support/core_ext/benchmark.rb:14:in `block in ms'
/usr/lib/ruby/2.6.0/benchmark.rb:308:in `realtime'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.5/lib/active_support/core_ext/benchmark.rb:14:in `ms'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.5/lib/active_support/benchmarkable.rb:43:in `benchmark'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/blacklight-spotlight-2.13.0/app/models/spotlight/resource.rb:50:in `reindex'
/opt/dpul/releases/20210917182847/app/models/iiif_resource.rb:69:in `reindex'
/opt/dpul/releases/20210917182847/app/jobs/spotlight/reindex_job.rb:35:in `block in perform'
/opt/dpul/releases/20210917182847/app/jobs/spotlight/reindex_job.rb:34:in `each'
/opt/dpul/releases/20210917182847/app/jobs/spotlight/reindex_job.rb:34:in `perform'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activejob-5.2.4.5/lib/active_job/execution.rb:39:in `block in perform_now'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.5/lib/active_support/callbacks.rb:109:in `block in run_callbacks'
/opt/dpul/releases/20210917182847/app/jobs/spotlight/reindex_job.rb:24:in `block in <class:ReindexJob>'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.5/lib/active_support/callbacks.rb:118:in `instance_exec'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.5/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/i18n-1.8.10/lib/i18n.rb:309:in `with_locale'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activejob-5.2.4.5/lib/active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.5/lib/active_support/callbacks.rb:118:in `instance_exec'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.5/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activejob-5.2.4.5/lib/active_job/logging.rb:26:in `block (4 levels) in <module:Logging>'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.5/lib/active_support/notifications.rb:168:in `block in instrument'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.5/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.5/lib/active_support/notifications.rb:168:in `instrument'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activejob-5.2.4.5/lib/active_job/logging.rb:25:in `block (3 levels) in <module:Logging>'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activejob-5.2.4.5/lib/active_job/logging.rb:46:in `block in tag_logger'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.5/lib/active_support/tagged_logging.rb:71:in `block in tagged'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.5/lib/active_support/tagged_logging.rb:28:in `tagged'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.5/lib/active_support/tagged_logging.rb:71:in `tagged'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activejob-5.2.4.5/lib/active_job/logging.rb:46:in `tag_logger'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activejob-5.2.4.5/lib/active_job/logging.rb:22:in `block (2 levels) in <module:Logging>'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.5/lib/active_support/callbacks.rb:118:in `instance_exec'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.5/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.5/lib/active_support/callbacks.rb:136:in `run_callbacks'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activejob-5.2.4.5/lib/active_job/execution.rb:38:in `perform_now'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activejob-5.2.4.5/lib/active_job/execution.rb:18:in `perform_now'
/opt/dpul/releases/20210917182847/app/models/iiif_resource.rb:63:in `save_and_index_now'
/opt/dpul/releases/20210917182847/app/jobs/iiif_ingest_job.rb:24:in `ingest'
/opt/dpul/releases/20210917182847/app/jobs/iiif_ingest_job.rb:8:in `block in perform'
/opt/dpul/releases/20210917182847/app/jobs/iiif_ingest_job.rb:7:in `each'
/opt/dpul/releases/20210917182847/app/jobs/iiif_ingest_job.rb:7:in `perform'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activejob-5.2.4.5/lib/active_job/execution.rb:39:in `block in perform_now'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.5/lib/active_support/callbacks.rb:109:in `block in run_callbacks'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/i18n-1.8.10/lib/i18n.rb:314:in `with_locale'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activejob-5.2.4.5/lib/active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.5/lib/active_support/callbacks.rb:118:in `instance_exec'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.5/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activejob-5.2.4.5/lib/active_job/logging.rb:26:in `block (4 levels) in <module:Logging>'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.5/lib/active_support/notifications.rb:168:in `block in instrument'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.5/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.5/lib/active_support/notifications.rb:168:in `instrument'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activejob-5.2.4.5/lib/active_job/logging.rb:25:in `block (3 levels) in <module:Logging>'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activejob-5.2.4.5/lib/active_job/logging.rb:46:in `block in tag_logger'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.5/lib/active_support/tagged_logging.rb:71:in `block in tagged'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.5/lib/active_support/tagged_logging.rb:28:in `tagged'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.5/lib/active_support/tagged_logging.rb:71:in `tagged'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activejob-5.2.4.5/lib/active_job/logging.rb:46:in `tag_logger'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activejob-5.2.4.5/lib/active_job/logging.rb:22:in `block (2 levels) in <module:Logging>'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.5/lib/active_support/callbacks.rb:118:in `instance_exec'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.5/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.5/lib/active_support/callbacks.rb:136:in `run_callbacks'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activejob-5.2.4.5/lib/active_job/execution.rb:38:in `perform_now'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activejob-5.2.4.5/lib/active_job/execution.rb:24:in `block in execute'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.5/lib/active_support/callbacks.rb:109:in `block in run_callbacks'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activejob-5.2.4.5/lib/active_job/railtie.rb:28:in `block (4 levels) in <class:Railtie>'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.5/lib/active_support/execution_wrapper.rb:87:in `wrap'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.5/lib/active_support/reloader.rb:73:in `block in wrap'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.5/lib/active_support/execution_wrapper.rb:83:in `wrap'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.5/lib/active_support/reloader.rb:72:in `wrap'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activejob-5.2.4.5/lib/active_job/railtie.rb:27:in `block (3 levels) in <class:Railtie>'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.5/lib/active_support/callbacks.rb:118:in `instance_exec'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.5/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.5/lib/active_support/callbacks.rb:136:in `run_callbacks'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activejob-5.2.4.5/lib/active_job/execution.rb:22:in `execute'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activejob-5.2.4.5/lib/active_job/queue_adapters/sidekiq_adapter.rb:42:in `perform'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/sidekiq-5.2.9/lib/sidekiq/processor.rb:192:in `execute_job'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/sidekiq-5.2.9/lib/sidekiq/processor.rb:165:in `block (2 levels) in process'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/sidekiq-5.2.9/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/ddtrace-0.49.0/lib/ddtrace/contrib/sidekiq/server_tracer.rb:42:in `block in call'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/ddtrace-0.49.0/lib/ddtrace/tracer.rb:287:in `trace'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/ddtrace-0.49.0/lib/ddtrace/contrib/sidekiq/server_tracer.rb:23:in `call'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/sidekiq-5.2.9/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/honeybadger-4.8.0/lib/honeybadger/plugins/sidekiq.rb:10:in `call'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/sidekiq-5.2.9/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/sidekiq-5.2.9/lib/sidekiq/middleware/chain.rb:133:in `invoke'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/sidekiq-5.2.9/lib/sidekiq/processor.rb:164:in `block in process'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/sidekiq-5.2.9/lib/sidekiq/processor.rb:137:in `block (6 levels) in dispatch'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/sidekiq-5.2.9/lib/sidekiq/job_retry.rb:109:in `local'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/sidekiq-5.2.9/lib/sidekiq/processor.rb:136:in `block (5 levels) in dispatch'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/sidekiq-5.2.9/lib/sidekiq/rails.rb:43:in `block in call'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.5/lib/active_support/execution_wrapper.rb:87:in `wrap'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.5/lib/active_support/reloader.rb:73:in `block in wrap'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.5/lib/active_support/execution_wrapper.rb:87:in `wrap'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.5/lib/active_support/reloader.rb:72:in `wrap'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/sidekiq-5.2.9/lib/sidekiq/rails.rb:42:in `call'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/sidekiq-5.2.9/lib/sidekiq/processor.rb:132:in `block (4 levels) in dispatch'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/sidekiq-5.2.9/lib/sidekiq/processor.rb:250:in `stats'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/sidekiq-5.2.9/lib/sidekiq/processor.rb:127:in `block (3 levels) in dispatch'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/sidekiq-5.2.9/lib/sidekiq/job_logger.rb:8:in `call'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/sidekiq-5.2.9/lib/sidekiq/processor.rb:126:in `block (2 levels) in dispatch'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/sidekiq-5.2.9/lib/sidekiq/job_retry.rb:74:in `global'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/sidekiq-5.2.9/lib/sidekiq/processor.rb:125:in `block in dispatch'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/sidekiq-5.2.9/lib/sidekiq/logging.rb:48:in `with_context'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/sidekiq-5.2.9/lib/sidekiq/logging.rb:42:in `with_job_hash_context'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/sidekiq-5.2.9/lib/sidekiq/processor.rb:124:in `dispatch'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/sidekiq-5.2.9/lib/sidekiq/processor.rb:163:in `process'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/sidekiq-5.2.9/lib/sidekiq/processor.rb:83:in `process_one'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/sidekiq-5.2.9/lib/sidekiq/processor.rb:71:in `run'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/sidekiq-5.2.9/lib/sidekiq/util.rb:16:in `watchdog'
/opt/dpul/shared/bundle/ruby/2.6.0/gems/sidekiq-5.2.9/lib/sidekiq/util.rb:25:in `block in safe_thread'
```

Job Parameters:

```json
  "job" => {
    "class" => "ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper",
    "wrapped" => "IIIFIngestJob",
    "queue" => "default",
    "args" => [{
      "job_class" => "IIIFIngestJob",
      "job_id" => "dec24d78-c0e8-4e83-b1fc-f743df939e2d",
      "provider_job_id" => nil,
      "queue_name" => "default",
      "priority" => nil,
      "arguments" => [
        "https://figgy.princeton.edu/concern/ephemera_folders/8b19c5df-5e76-4506-bd62-59f27a44f520/manifest",
        {"_aj_globalid" => "gid://pomegranate/Spotlight::Exhibit/97"},
        nil
      ],
      "executions" => 0,
      "locale" => "en"
    }],
```

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/51733/faults/81459978)

**Comment by hackartisan** [comment]
It looks like a bunch of these have null titles. 

in the "lae" exhibit.

examples:
- https://figgy.princeton.edu/catalog/4d969fc8-4c3f-4295-b3d4-e43b37d9df9c.jsonld
- https://figgy.princeton.edu/catalog/a4c8879a-bf51-4d2b-9c41-7667c5e2c4ef.jsonld

**Comment by hackartisan** [comment]
close in favor of https://github.com/pulibrary/dpul/issues/1399
