### ISSUE TITLE
Deprecation: search_fields

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/dpul#990]
```
DEPRECATION WARNING: search_fields is deprecated and will be removed from a future release (removed without replacement). (called from block in _app_views_catalog__search_form_html_erb___82315862898
9550518_70228025109240 at /Users/eliotj/Documents/Repositories/dpul/app/views/catalog/_search_form.html.erb:6) (43 times); e.g.:
    /Users/eliotj/Documents/Repositories/dpul/app/views/catalog/_search_form.html.erb:6:in `block in _app_views_catalog__search_form_html_erb___823158628989550518_70228025109240'
    /Users/eliotj/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/actionview-5.2.4.5/lib/action_view/helpers/capture_helper.rb:41:in `block in capture'
    /Users/eliotj/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/actionview-5.2.4.5/lib/action_view/helpers/capture_helper.rb:205:in `with_output_buffer'
    /Users/eliotj/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/actionview-5.2.4.5/lib/action_view/helpers/capture_helper.rb:41:in `capture'
    /Users/eliotj/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/actionview-5.2.4.5/lib/action_view/helpers/form_tag_helper.rb:72:in `form_tag'
```

**Comment by eliotjordan** [comment]
Fixed in the upgrade process.
