### ISSUE TITLE
Deprecation: search_field_options_for_select

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/dpul#991]
```
DEPRECATION WARNING: search_field_options_for_select is deprecated and will be removed from a future release (removed without replacement). (called from search_fields at /Users/eliotj/.asdf/installs
/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/blacklight-7.19.2/app/helpers/blacklight/configuration_helper_behavior.rb:25) (43 times); e.g.:
    /Users/eliotj/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/blacklight-7.19.2/app/helpers/blacklight/configuration_helper_behavior.rb:25:in `search_fields'
    /Users/eliotj/Documents/Repositories/dpul/app/views/catalog/_search_form.html.erb:6:in `block in _app_views_catalog__search_form_html_erb___823158628989550518_70228025109240'
    /Users/eliotj/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/actionview-5.2.4.5/lib/action_view/helpers/capture_helper.rb:41:in `block in capture'
    /Users/eliotj/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/actionview-5.2.4.5/lib/action_view/helpers/capture_helper.rb:205:in `with_output_buffer'
    /Users/eliotj/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/actionview-5.2.4.5/lib/action_view/helpers/capture_helper.rb:41:in `capture'
```

**Comment by eliotjordan** [comment]
Fixed.
